### ISSUE TITLE
Is utils/ddp_utils.py missing?

### ISSUE THREAD

**Issue by drscotthawley** [Rongjiehuang/FastDiff#2]
Dear Rongjie, thank you for sharing your code with community, and congratulations on having your paper accepted.

When I try to follow the instructions for inference on wav files, I get the following error:

``bash
  File "/home/ubuntu/FastDiff/utils/trainer.py", line 19, in <module>
    from utils.ddp_utils import DDP
ModuleNotFoundError: No module named 'utils.ddp_utils'
```
When I look in the utils/ directory, I see a `tts_utils.py` but no `ddp_utils.py`.  I don't find that file anywhere in this repo.

Is this supposed to be the same as [NATSpeech's ddp_utils](https://github.com/NATSpeech/NATSpeech/blob/f209f8410438bd73232ddc4997768e49ec2b1b84/utils/commons/ddp_utils.py)? 

Thanks.

**Comment by Rongjiehuang** [comment]
Hi, thanks for your interest.
You're right that `ddp_utils.py` is the same as that in NATSpeech repo, and this missing file has been updated.

**Comment by drscotthawley** [comment]
Ok thank you! 
Closing.
