### ISSUE TITLE
Pretrained model is lost

### ISSUE THREAD

**Issue by cantabile-kwok** [Rongjiehuang/FastDiff#27]
Hi, it seems the link to the pretrained model is lost : ( 
Could you help fix it? Thanks in advance!
![image](https://github.com/Rongjiehuang/FastDiff/assets/58417810/70b314b2-b341-4fb8-bca0-3783991724ba)

**Comment by zrdthu** [comment]
Somehow the link has expired. I managed to find the checkpoint from another source on HuggingFace: https://huggingface.co/Rongjiehuang/ProDiff/tree/main/checkpoints/FastDiff

**Comment by Rongjiehuang** [comment]
please find here https://huggingface.co/Rongjiehuang/FastDiff
