### ISSUE TITLE
Pre-defined noise schedule

### ISSUE THREAD

**Issue by yahshibu** [Rongjiehuang/FastDiff#9]
Thank you for making your code publicly available!

I have a question about the pre-defined noise schedule. [The paper](https://arxiv.org/pdf/2204.09934.pdf) says ```β = Linear(1e−4, 0.005, 1000)``` was used (Table 7). On the other hand, the default setting of this repository is ```β = Linear(0.000001, 0.01, 1000)```. https://github.com/Rongjiehuang/FastDiff/blob/f737e17e344923a7ec60507b289abd756f76000a/modules/FastDiff/config/FastDiff.yaml#L52-L54

Which setup is your recommendation?

To my understanding, the noise-predictor-derived noise schedule depends on a trained score network. It means the noise-predictor-derived noise schedule depends on the pre-defined noise schedule. Is this correct?

**Comment by Rongjiehuang** [comment]
Hi, this schedule is not such sensitive. We have tested both`β = Linear(1e-6, 0.005, 1000)` (in paper), or `β = Linear(1e-6, 0.01, 1000)` (this repo).
